---

- name: install the gpg key for kubeadm
  apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present

- name: add the kubeadm apt repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: install kubeadm and required prereqs
  apt: name={{ item }} update_cache=yes state=present state=latest
  with_items:
  - docker.io
  - kubelet
  - kubeadm
  - kubectl
  - kubernetes-cni

- name: setting up docker unit drop-in dir
  file: path=/etc/systemd/system/docker.service.d state=directory
  when: docker_shared_mounts

- name: setting up docker shared mounts
  template: src="10-docker-shared-mounts.conf.j2" dest="/etc/systemd/system/docker.service.d/10-docker-shared-mounts.conf" mode=0640
  when: docker_shared_mounts
  register: dsm

- name: reload systemd config
  command: systemctl daemon-reload
  when: dsm.changed

- name: restart docker service
  service: name=docker state=restarted
  when: dsm.changed

- name: add kubelet.service drop-in for hostname override
  template: src="15-hostname-override.conf.j2" dest="/etc/systemd/system/kubelet.service.d/15-hostname-override.conf" mode=0640
  when: kubelet_hostname_override
  register: kho

- name: reload systemd config
  command: systemctl daemon-reload
  when: kho.changed

- name: restart kubelet service
  service: name=kubelet state=restarted
  when: kho.changed
